### ISSUE TITLE
Add auto-repeat to `Controller`, possibly as `Controller::setAutoRepeat(Button button, bool enable, uint32_t delayMs = 250, uint32_t repeatMs = 50)`

### ISSUE THREAD

**Issue by and3rson** [and3rson/lilka#100]

**Comment by frostmorn** [comment]
я вже пробував щось подібне, можна поряд з перевіркою на debounce чистити state

**Comment by and3rson** [comment]
> я вже пробував щось подібне, можна поряд з перевіркою на debounce чистити state

@frostmorn Так, десь там поруч і думав це додати. В структурі стану кожнох кнопки вже є поле `time`, тому можна просто всередині `inputTask` перевіряти, чи вже минуло `delayMs` і тоді робити `justPressed = true` кожні repeatMs.

Потрібно буде ще додати в цю структуру поле `lastRepeat` (щоб мати змогу міряти інтервал повторення), а також додати туди поля `delay` і `repeat`, які за замовчуванням 0 (не повторювати).
