### ISSUE TITLE
SD card bug(menu -> bmp, txt files)

### ISSUE THREAD

**Issue by black-ghost-off** [and3rson/lilka#121]
При натску в sd карті на файли TXT, BMP лілка зависає до скидання, нічого на екранні не відображається, повторний натиск A повертає в нормальний стан меню.

**Comment by frostmorn** [comment]
В нас немає коду який би оброблював BMP\TXT формат, в цьому випадку має з'явитися на екрані інформація про розмір файла в байтах.
