### ISSUE TITLE
APP_FLAG_FULLSCREEN ignored by panel

### ISSUE THREAD

**Issue by noisedsn** [and3rson/lilka#128]
Не зникає панель під час роботи додатків, в яких встановлено APP_FLAG_FULLSCREEN та НЕ встановлено APP_FLAG_INTERLACED, таких як NesApp, ModPlayerApp, AbstractLuaRunnerApp та інші. В результаті, вгорі екрана відображається панель, а додаток рендериться зміщеним на 24 пікселі вниз і верхні рядки 24...48 займають артефакти від накладання нижньої частини кадру додатка на верхню.

![20241213_095905](https://github.com/user-attachments/assets/10c78ea2-743e-4ab4-a58f-4ac641d4b85e)

Відчуваю, що це, можливо, якось пов'язано зі змінами щодо інтерлейсу. Якщо примусово малювати все через інтерлейс, то баг зникає в усіх додатках. Для цього я спробував замінити в файлі appmanager.cpp
                    lilka::display.drawCanvas(app->backCanvas);
на 
                    lilka::display.drawCanvasInterlaced(app->backCanvas, app->frame % 2);

На жаль, докопатися до суті і пофіксити коректно моїх скромних знань не вистачило...

**Comment by frostmorn** [comment]
can't reproduce

![screenshot_19700101_000013](https://github.com/user-attachments/assets/ff08735a-e2ed-4aba-a279-de28b9c997a4)
![screenshot_19700101_000125](https://github.com/user-attachments/assets/2be432b4-3698-4854-a86d-1eb5b33f38e4)
![screenshot_19700101_000121](https://github.com/user-attachments/assets/f1a17461-f185-40e0-a676-4af5ebc66951)
![screenshot_19700101_000122](https://github.com/user-attachments/assets/5b70a018-b773-457f-8bb8-829b58f7bab8)
![screenshot_19700101_002036](https://github.com/user-attachments/assets/29021787-c529-4c1d-b32e-0c348225768b)
![screenshot_19700101_000043](https://github.com/user-attachments/assets/d2f83d0c-e534-4ed0-be1c-568f2c4e5142)
![screenshot_20241213_231501](https://github.com/user-attachments/assets/8f1d0f2f-8745-4ab2-82e9-857bf029eccd)

**Comment by noisedsn** [comment]
> can't reproduce

А скріншоти і у мене красиві. У фреймбуфері дані коректні. здається, а на екрані мерехтять 24-48 рядки і панель стирчить у повноекранних додатках (крім лілтрекера, до речі). Може якісь таймінги в залізі, чи глюки компілятора - хтозна, я не справжній програміст. Поки що вдалося некрасиво пофіксити, додавши у display.cpp ще одну функцію аналогічну тій що відмальовує інтерлейс:

void Display::drawCanvasBad(Canvas* canvas) {
    this->startWrite();
    for (int y = 0; y < canvas->height(); y ++ ) {
        this->writeAddrWindow(canvas->x(), canvas->y() + y, canvas->width(), 1);
        this->writePixels(canvas->getFramebuffer() + y * canvas->width(), canvas->width());
    }
    this->endWrite();
}

ну і в display.h:
    void drawCanvasBad(Canvas* canvas);

Після чого в appmanager.cpp:
lilka::display.drawCanvas(app->backCanvas);
на
lilka::display.drawCanvasBad(app->backCanvas);

**Comment by noisedsn** [comment]
Тим не менш, зі штатною функцією глюк є, з моїм костилем - немає. Не одразу помітив, що панель не відображається як звичайно, то просто "слід" від неї, на якому не йде годинник і нічого не міняється.

https://github.com/user-attachments/assets/2ec24964-374b-4f5c-b61f-900b69038e58

Таке враження наче десь якась команда на зміну координат губиться, а моя тормозна функція трохи все сповільнила. Пробував потикати в різні місця delay - не допомагає.  Замовив другий дисплей, приїде - спробую з ним, може мені глючний попався.

**Comment by noisedsn** [comment]
Мені дико соромно, в мене був не найновіший зріз репозиторію. В останній прошивці все коректно.
