### ISSUE TITLE
UI components do not check or process insufficient space problem

### ISSUE THREAD

**Issue by frostmorn** [and3rson/lilka#85]
lilka:Menu-> title
lilka:Menu->item->optional postfix
most lilkely lilka::Alert and others also affected.
![screenshot_19700101_000414](https://github.com/and3rson/lilka/assets/15167344/7fb9282d-3a52-49e2-9e15-ed81848c1ccd)

**Comment by and3rson** [comment]
Мабуть, варто зробити якийсь скролінг тексту
